name: flutter_build_version
description: Flutter/Dart version library
version: 0.0.1
homepage: https://github.com/kilroy80/flutter_build_version

environment:
  sdk: ">=2.17.0 <5.0.0"

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0